spring.application.name=springsecutiry
spring.config.import = optional:file:env.properties
# server config
server.port = ${PORT}
# db config
spring.datasource.url = ${DB_URL}
spring.datasource.username= ${DB_USERNAME}
spring.datasource.password= ${DB_PASSWORD}
spring.datasource.driver-class-name= org.postgresql.Driver
# hibernate
spring.jpa.hibernate.ddl-auto = update
#cloudinary
#CLOUDINARY_URL = cloudinary://${CLOUDINARY_APIKEY}:${CLOUDINARY_SECRET}@sejcn1v6
#cloudinary.name = ${CLOUDINARY_NAME}
#cloudinary.api.secret =${CLOUDINARY_SECRET}
#cloudinary.api.key =${CLOUDINARY_APIKEY}